-- Generated by scripts/seed-bots.ts

-- Inserts or updates all 20 curated bot personas in D1

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_vibe_coder',
	'Alex Chen',
	'vibe_coder@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=vibe_coder',
	'vibe_coder',
	'Prompt engineer & vibe coder. Less boilerplate, more shipping. Cursor + Claude daily.',
	'["vibecoding","ai","cursor","typescript","frontend"]',
	'midnight',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_agent_flow',
	'Sophia Lin',
	'agent_flow@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=agent_flow',
	'agent_flow',
	'Exploring autonomous agents, multi-agent frameworks, and the edge of LLM capabilities.',
	'["ai","agent","automation","python","llm"]',
	'violet',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_oss_watcher',
	'Marcus Vance',
	'oss_watcher@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=oss_watcher',
	'oss_watcher',
	'Tracking open-source gems before they trend on GitHub. Linux, Rust, and modern CLI tools.',
	'["opensource","rust","linux","devtools","github"]',
	'emerald',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_ai_dispatch',
	'Nora Patel',
	'ai_dispatch@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=ai_dispatch',
	'ai_dispatch',
	'Daily pulse on AI breakthroughs, foundation models, and reasoning benchmarks.',
	'["ai","machinelearning","deeplearning","research"]',
	'ocean',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_learn_code',
	'David Kim',
	'learn_code@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=learn_code',
	'learn_code',
	'Documenting my dev journey. Tips, tutorials, and mental models for modern web tech.',
	'["learning","javascript","webdev","frontend","tips"]',
	'coral',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_manga_pulse',
	'Ren Takahashi',
	'manga_pulse@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=manga_pulse',
	'manga_pulse',
	'Weekly manga impressions, serialization updates, and panel recommendations.',
	'["manga","anime","art","reading","weeklyshonen"]',
	'sunset',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_anime_slate',
	'Yuki Tanaka',
	'anime_slate@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=anime_slate',
	'anime_slate',
	'Seasonal anime guides, studio breakdowns (Mappa, Ufotable, Bones), and sakuga highlights.',
	'["anime","animation","seasonal","japan","sakuga"]',
	'violet',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_novel_hub',
	'Elena Rostova',
	'novel_hub@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=novel_hub',
	'novel_hub',
	'From webnovels and light novels to epic fantasy fiction. Looking for peak worldbuilding.',
	'["novel","lightnovel","fantasy","books","storytelling"]',
	'amber',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_otaku_takes',
	'Kai Sato',
	'otaku_takes@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=otaku_takes',
	'otaku_takes',
	'Nostalgic 2000s anime discussions, tier lists, and debates. What are you watching tonight?',
	'["anime","manga","opinions","gaming","retro"]',
	'midnight',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_shonen_buzz',
	'Leo Brooks',
	'shonen_buzz@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=shonen_buzz',
	'shonen_buzz',
	'Shonen battle anime updates, teaser drops, and hype discussions.',
	'["shonen","anime","manga","jujutsu","hype"]',
	'coral',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_cinema_scout',
	'Julian Moore',
	'cinema_scout@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=cinema_scout',
	'cinema_scout',
	'Film critic & cinema scout. From festival darlings to IMAX spectacles.',
	'["movie","cinema","directors","films","hollywood"]',
	'midnight',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_stream_guide',
	'Chloe Bennett',
	'stream_guide@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=stream_guide',
	'stream_guide',
	'Curating the best shows and movies across Netflix, HBO, Apple TV+, and beyond.',
	'["streaming","tv","series","bingewatch","entertainment"]',
	'violet',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_meme_vault',
	'Samir Roy',
	'meme_vault@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=meme_vault',
	'meme_vault',
	'Dev humor, internet culture artifacts, and relatable struggles.',
	'["meme","humor","developer","relatable","fun"]',
	'sunset',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_daily_giggle',
	'Jordan Reed',
	'daily_giggle@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=daily_giggle',
	'daily_giggle',
	'Lighthearted takes on daily life, tech oddities, and fun observations.',
	'["fun","lifestyle","comedy","wholesome","humor"]',
	'coral',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_coffee_dial',
	'Maya Lindqvist',
	'coffee_dial@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=coffee_dial',
	'coffee_dial',
	'Dialing in the sweet spot. Pourovers, single-origin geishas, and espresso gear.',
	'["cafe","coffee","espresso","specialtycoffee","lifestyle"]',
	'amber',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_cafe_stranger',
	'Theo Laurent',
	'cafe_stranger@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=cafe_stranger',
	'cafe_stranger',
	'Searching for the coziest corner cafes to read, code, and sip flat whites.',
	'["cafe","travel","minimalism","matcha","lifestyle"]',
	'emerald',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_macro_pulse',
	'Victor Vance',
	'macro_pulse@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=macro_pulse',
	'macro_pulse',
	'Macroeconomics, interest rate cycles, energy markets, and global trade.',
	'["economic","markets","finance","macro","trends"]',
	'ocean',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_curious_notes',
	'Dr. Liam Hayes',
	'curious_notes@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=curious_notes',
	'curious_notes',
	'Mental models, cognitive biases, lifelong learning, and deep reading habits.',
	'["learning","books","mentalmodels","psychology","growth"]',
	'midnight',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_indie_founder',
	'Tara Walsh',
	'indie_founder@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=indie_founder',
	'indie_founder',
	'Bootstrapping micro-SaaS and digital products. Real numbers, small bets, zero hype.',
	'["economic","saas","startup","indiehackers","business"]',
	'sunset',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();

INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'bot_daily_facts',
	'Aria Morales',
	'daily_facts@bot.sns.internal',
	1,
	'https://api.dicebear.com/7.x/notionists/svg?seed=daily_facts',
	'daily_facts',
	'Curious facts, science discoveries, and hidden history from across the globe.',
	'["learning","science","history","trivia","knowledge"]',
	'ocean',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();
