import fs from 'node:fs'
import path from 'node:path'
import { BOT_PERSONAS } from '../src/lib/server/bot/personas.ts'

function escape_sql(str: string): string {
	return str.replace(/'/g, "''")
}

export function generate_seed_sql(): string {
	const statements: string[] = [
		'-- Generated by scripts/seed-bots.ts',
		'-- Inserts or updates all 20 curated bot personas in D1',
	]

	for (const bot of BOT_PERSONAS) {
		const interests_json = JSON.stringify(bot.interests)
		const stmt = `INSERT INTO user (
	id, name, email, email_verified, image, username, bio, interests, banner_color, onboarded, created_at, updated_at
) VALUES (
	'${escape_sql(bot.id)}',
	'${escape_sql(bot.name)}',
	'${escape_sql(bot.email)}',
	1,
	'${escape_sql(bot.image)}',
	'${escape_sql(bot.username)}',
	'${escape_sql(bot.bio)}',
	'${escape_sql(interests_json)}',
	'${escape_sql(bot.bannerColor)}',
	1,
	unixepoch(),
	unixepoch()
) ON CONFLICT(id) DO UPDATE SET
	name = excluded.name,
	username = excluded.username,
	bio = excluded.bio,
	interests = excluded.interests,
	banner_color = excluded.banner_color,
	image = excluded.image,
	onboarded = 1,
	updated_at = unixepoch();`
		statements.push(stmt)
	}

	return statements.join('\n\n') + '\n'
}

function run() {
	const out_path = path.resolve(process.cwd(), 'scripts/seed-bots.sql')
	const sql = generate_seed_sql()
	fs.writeFileSync(out_path, sql, 'utf8')
	console.log(`✅ Generated seed SQL with ${BOT_PERSONAS.length} bots at ${out_path}`)
	console.log('\nTo apply to local D1:')
	console.log('  pnpm wrangler d1 execute sns-project-db --local --file=scripts/seed-bots.sql\n')
	console.log('To apply to remote (production) D1:')
	console.log('  pnpm wrangler d1 execute sns-project-db --remote --file=scripts/seed-bots.sql\n')
}

run()
